spring:
  cloud:
    gcp:
      secretmanager:
        enabled: true
  profiles: 
    active: local

  datasource:
    password:  "${sm://projects/121262051629/secrets/db-password-secret/versions/1}"
  
logging:
  file:
    name: log/app.log


---
spring:
  output:
    ansi:
      enabled: DETECT
  data:
    mongodb: 
      uri: mongodb+srv://alina:${spring.datasource.password}@cluster0.guf1c.mongodb.net/alina?retryWrites=true&w=majority
  config:
    activate:
      on-profile:
      - local
server:
  port : 8080
  
logging:
  level: 
    '[org.springframework.web]': INFO
    '[com.kali.app.BusinessLayer.AlinaServiceImpl]': DEBUG