spring:
  profiles: 
    active: local 

logging:
  file:
    name: log/app.log
  
---
spring:
  output:
    ansi:
      enabled: DETECT
  data:
    mongodb: 
      uri:  mongodb://localhost:27017/alina?readPreference=primary&authSource=admin&appname=MongoDB%20Compass&directConnection=true&ssl=false
  config:
    activate:
      on-profile:
      - local
server:
  port : 8888
  
logging:
  level: 
    '[org.springframework.web]': INFO
    '[com.kali.app.BusinessLayer.AlinaServiceImpl]': DEBUG
  
---
spring:
  config:
    activate:
      on-profile:
      - dev
server:
  port : 8081

logging:
  level:
    root: INFO
    '[org.springframework.web]': INFO


---
spring:
  config:
    activate:
      on-profile:
      - docker
  data:
    mongodb:
      host: mongo_db
server:
  port : 8082

logging:
  level:
    root: info
    '[com.kali.app.BusinessLayer.AlinaServiceImpl]': DEBUG
