name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    #Setup JDK
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
          java-version: '11'
          distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean package -f app/pom.xml
      
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
        
    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        context: ./app
    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker
    # Build the Docker image
    - name: Build
      run: |-
        docker build --tag "gcr.io/${{ secrets.GCP_PROJECT_ID }}/app:$GITHUB_SHA" app/.
    # Push the Docker image to Google Container Registry
    - name: Publish
      if: github.ref == 'refs/heads/main'
      run: |-
        docker push "gcr.io/${{ secrets.GCP_PROJECT_ID }}/app:$GITHUB_SHA"
